### ISSUE TITLE
Homepage Brainstorm

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website-design#101]

**Comment by nrhsinclair** [comment]
Here are a couple of homepage ideas on attached images. Also includes some navigation ideas. Both images are for brainstorming. Builds on discussion last week task force discussion and goals that were discussed - W3C and WAI relationship and purpose. 
Also included a prominent link to a map of all resources. See images.

![wai homepage full menus](https://user-images.githubusercontent.com/26551556/31787346-7b34cfa4-b4d9-11e7-99d9-9993d2abc915.png)

![wai homepage 2 popup menus](https://user-images.githubusercontent.com/26551556/31787362-85f58fc8-b4d9-11e7-999f-be116f4c83a1.png)

**Comment by VivienneConway** [comment]
These look beautiful!  One question from me with my #ally hat on.  Can you tell me the option that has been selecting for showing keyboard/mouse focus?  It would be great to reverse the front/background colours.  Also has the method for the menu operation been discussed?  We have such a great opportunity to have this site used as a best case example.

 (Shortened Vivienne’s message to not show the email footer. — Eric)

**Comment by nrhsinclair** [comment]
I'm adding a 3rd version that has a section for "What's Going On/ News and Highlights" on the right.
![wai homepage with news](https://user-images.githubusercontent.com/26551556/31827642-528caa2e-b586-11e7-83d8-5cced02dcdd0.png)

**Comment by yatil** [comment]
@nrhsinclair Thanks. A lot of that could be done with re-arranging components that we already have, I think.

**Comment by nrhsinclair** [comment]
Yes, I agree, taking the current design and rearranging some things.

**Comment by bakkenb** [comment]
Attached are 2 similar PDF versions of a vision I have had about the site for some time now. This needs some good design touch ups (colors) and is not the complete home page. It is just what I think we should welcome people with at the top of the page. I took some of the language from Norah's examples to describe the sections (thanks Norah!)

It will meet the need of letting people know that WAI is created by W3C and even maintained by EOWG. It also gives them one of 5 portals to choose for their purpose of visiting the site. Each portal would have a landing page that describes the type of resources that are in that particular section (with links and explanations). This will help give users a quick look at the breadth and depth of what we have. 

Again, it needs some visual work and other help, but I just wanted to throw my ideas on the wall to see what can be used.

- Version 1 - [WAI Home Page-v1_BakkenB.pdf](https://github.com/w3c/wai-website-design/files/1415325/WAI.Home.Page-v1_BakkenB.pdf)
- Version 2 - [WAI Home Page-v2_BakkenB.pdf](https://github.com/w3c/wai-website-design/files/1415335/WAI.Home.Page-v2_BakkenB.pdf) - (same content just different background color)

**Comment by nrhsinclair** [comment]
I really like those sections Brent!

**Comment by shawna-slh** [comment]
Reminder that the updated home page goals (as discussed at 11 October Task Force telecon) are here: https://www.w3.org/WAI/EO/wiki/Redesign_-_October_Revisions#Home_page

**Comment by yatil** [comment]
We have a new mock-up.
