### ISSUE TITLE
[nav] Standards Overview page

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#103]
From https://www.w3.org/WAI/EO/wiki/Redesign_-_October_Revisions : 

**(new doc) Standards/Guidelines — first link is an overview page**
* 🚨 The Components of Web Accessibility page? Or the link Standards/Guidelines? If that got an overview page, shouldn’t the other main nav items get their own overview pages, too? – Eric
* I think we need a new page that is titled **Accessibility Standards/Guidelines Overview**, and can be in the nav probably just "**Overview**". I do _not_ think we need to have Overview pages for all of the other nav items. ~Shawn

/me  's suggestion comes from previous WG discussions and supported by UT :-)

@yatil - Please create a placeholder page, and I'll populate it when I can get to it &mdash; hopefully in the next day or two. Thanks!

**Comment by yatil** [comment]
>  If that got an overview page, shouldn’t the other main nav items get their own overview pages, too? – Eric

For context, that comment was if the actual Standards/Guidelines link worked differently than the other main navigation items. If we add a page Overview with its own sub-nav link, that’s totally :cool: with me! 😎

**Comment by yatil** [comment]
Added here: https://github.com/w3c/wai-website/blob/master/pages/standards/index.md
