### ISSUE TITLE
Color of expand/collapse buttons

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website-design#104]
Some criticism that the icons are too bold. Unsure what to do about it. I certainly want consistency and easy discoverability of the feature.

See discussion in w3c/wai-intro-accessibility#5.

**Comment by lakeen** [comment]
I think this is a question for Alicia.  Decreasing the size of the icon could help.  The background color of the icon is causing the issue and needs to be consistent with link color so it's not a simple fix.

**Comment by yatil** [comment]
IIRC it uses the standard buttons with icons CSS, I can see if there is a good way to make them less heavy.

**Comment by shawna-slh** [comment]
+1 for less visually strong

brainstorm(=maybe a bad idea;-): Have the outline and the + link blue, and the fill color the background color.

**Comment by yatil** [comment]
@slhenry That’s basically what I did.

Note that it might only show up after the document has been edited (as the theme is only refreshed then).

**Comment by shawna-slh** [comment]
Pointer to one to look at?

**Comment by yatil** [comment]
@slhenry See https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/ – I am not 100% happy with the consistency of the position (especially with different heading levels), so I might change some positioning aspects in a later iteration.

**Comment by shawna-slh** [comment]
likey for now!
