### ISSUE TITLE
Define Video Thumbnails

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website-design#107]
We currently have no designs for video thumbs as implemented in w3c/wai-intro-accessibility#13

Challenges:

* Obviously Clickable.
* What happens when the link is clicked? (Autoplay yes or no?)
* Will the thumbnail have a play button on it?
* What about the video title? Where will it be displayed?

**Comment by yatil** [comment]
Fixed with #115.

**Comment by shawna-slh** [comment]
Thanks! Will be nice to have a consistent look & feel for them. :-)

In https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/#examples I find these too big. The fact that it is a picture automatically draws lots of attention, and the picture itself doesn't need to communicate meaning -- So I think it should be smaller.
However, I know that my settings do odd things with sizes -- so maybe I wouldn't think it too big in other configurations? I welcome different perspectives.

In any case, I think it would be good to have a few sizes options for different contexts, including one that is much smaller (potentially for places like highlights <https://www.w3.org/WAI/highlights/archive>), and bigger (for places like Perspectives overview https://w3c.github.io/wai-website/perspective-videos/).

**Comment by shawna-slh** [comment]
ftr: I'm a bit hesitant having an arrow play button in cases where clicking it goes to a web page instead of automatically starting a video.

However, I do see that other places on the Web, and it doesn't bother me too much.

I'm fine leaving as is for now.

If someone is looking for a research &/or design project, maybe they want to look into options...

**Comment by shawna-slh** [comment]
Just noted in https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/ that would like less space above video thumbnail so close proximity with intro above.
(can be low priority).

**Comment by yatil** [comment]
> ftr: I'm a bit hesitant having an arrow play button in cases where clicking it goes to a web page instead of automatically starting a video.

I would not have been opposed to having an inline video player on the page. Maybe I put the play button in one of the corners to make it clear that this is a link to a video.

> Just noted in https://w3c.github.io/wai-intro-accessibility/fundamentals/accessibility-intro/ that would like less space above video thumbnail so close proximity with intro above.
(can be low priority).

The spacing is a paragraph spacing. Less spacing will look weird in other situations.

**Comment by yatil** [comment]
Oh, just seeing your first comment on the sizes: We never did define anything about those thumbnails. I took the size of the thumbnails that you added and deducted from there.

Please define all variations and sizes so that there is a way to implement them. We cannot go around and iterate on those at this stage of the project.
