### ISSUE TITLE
Define On This Page Navigation

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website-design#108]
* Where to put it, see discussion here: w3c/wai-tutorials#548 
  * Inside `<main>` 
  * Before `<main>`
  * After `<main>`
  * Before `<h1>`
  * After `<h1>`
* How will the Page Contents look? Is standard box sufficient?

**Comment by shawna-slh** [comment]
After h1

Is main in redesign?

I think standard box -- isn't that was used for usability testing? -- whatever was, that fared well.

**Comment by yatil** [comment]
> After h1

Hm. I found Matt’s arguments for not having it directly in the main after the H1 very convincing… It doubles the content for screen readers who always have the option to navigate by headings.

> Is main in redesign?

Yes, main is in the redesign. Of course. Currently the source is (pseudo code):

```html
<main>
<nav>Sidebar Navigation
<article>Main content
  <nav> In Page Navigation
</article>
</main>
```

https://cl.ly/3M1w0I0O3j44

> I think standard box -- isn't that was used for usability testing? -- whatever was, that fared well.

OK, that works for me. Just wanted to make sure.

**Comment by yatil** [comment]
Close for now, I think we’re on the same page. :-)
