### ISSUE TITLE
asides, header, heading

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#113]
From https://github.com/w3c/wai-intro-accessibility/issues/18#issuecomment-360580931

> Another question, possibly for Eric, on the semantics of the `<aside>`s. Are we sticking with `<header>` tags within these contentinfo areas, or is it easier/better to have it follow logical heading structure, so in most cases an`<h3>` instead of a `<header>` tag? To be honest, I'm not overly familiar with the `<header>` use case, so it may be my ignorance here.

**Comment by yatil** [comment]
If we need headings, we can have headings inside the header. (And we do that in the accessibility intro.) Sometimes asides won’t have headings in the heading order. For consistency and styling reasons we have a header element that is describing the content of the box. This is according to the HTML standard of heading elements.
