### ISSUE TITLE
<dl> spacing

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#114]
I think by default we want more space between items in DL. see for example, https://w3c.github.io/wai-eval-overview/evaluation/#tools

**Comment by yatil** [comment]
I did not get any design for `<dl>` elements, so I have done nothing yet. I guess we don’t want spacing between multiple `<dd>` elements but space before the `<dt>` element.

**Comment by yatil** [comment]
Old site: `margin-top:.5em;`

**Comment by shawna-slh** [comment]
+1
