### ISSUE TITLE
"infographic" content

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#122]
W3C
The World Wide Web Consortium (W3C) develops international standards for the Web: HTML, CSS, and many more.

WAI
The W3C Web Accessibility Initiative (WAI) develops standards and support materials to help you understand and implement accessibility.

You
You can use W3C WAI resources to make your websites, applications, and other digital creations more accessible and usable to everyone.

**Comment by yatil** [comment]
Is this the content for the homepage? (We should have a repository for that…)

**Comment by yatil** [comment]
Added to home page here: https://github.com/w3c/wai-website/blob/master/index.md
