### ISSUE TITLE
Collect top tasks

### ISSUE THREAD

**Issue by charlottehwise** [w3c/wai-website-design#13]
Collect and refine a list of top tasks commonly performed on site by visitors (personas). This will be used to refine the IA and to inform the test plan for the benchmarking usability study.

See:
https://www.digitalgov.gov/2014/07/02/using-top-tasks-to-be-top-notch-federal-reserve-board-usability-case-study/
http://alistapart.com/article/what-really-matters-focusing-on-top-tasks
http://www.measuringu.com/blog/top-tasks.php
http://www.gerrymcgovern.com/new-thinking/top-task-analysis-evidence-over-opinion

**Comment by shawna-slh** [comment]
We have an old **[task list & task-user matrix](https://www.w3.org/WAI/redesign/tasks#matrix)** we developed for the 2005 redesign. Most of those are still relevant today. We will want to work on refining a top tasks list these days...

**Comment by shawna-slh** [comment]
Draft survey with open issues for @charlottehwise @James-Green and others: [5 Oct e-mail](https://lists.w3.org/Archives/Public/public-wai-eo-site/2016Oct/0000.html)

**Comment by shawna-slh** [comment]
Survey results https://www.w3.org/2002/09/wbs/35532/wai-site-tasks/results
