### ISSUE TITLE
beta flag

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#131]
Change "This is an unpublished draft preview. Please refer to our published website at w3.org/WAI/." to I think:

> This is beta redesign of the W3C WAI website. The published website is at [w3.org/WAI/](https://www.w3.org/WAI/)

It should go at the top and bottom.

Do we want to include in there links for comments: public-wai-eo-site@w3.org and https://github.com/w3c/wai-website-design/issues/new ?

**Comment by yatil** [comment]
@slhenry Do we want to keep the yellow background color or do we want to go less distracting (but keeping it obvious)?

**Comment by shawna-slh** [comment]
I think that yellow is good -- it's needs to be *very* obvious, and OK if a little distracting.

(But if you really want to try something else, I'm happy to look at it. :-)

(fyi, I was looking at http://www.bbc.co.uk/accessibility/ the other day and totally missed the "This page has been archived..." bit. Robert pointed it out to me.)

**Comment by yatil** [comment]
> (fyi, I was looking at http://www.bbc.co.uk/accessibility/ the other day and totally missed the "This page has been archived..." bit. Robert pointed it out to me.)

Yeah, that’s way to inobtrusive :-)
