### ISSUE TITLE
optional extra list spacing

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#132]
I'd like a style for lists with more space. Previously we had:

.listspaced li {
	margin-bottom: 1em;

@yatil, feel free to use whatever implementation, class, unit of measure, etc. that you think is best.

**Comment by shawna-slh** [comment]
(Then we can fix the br/s I put in https://github.com/w3c/wai-std-gl-overview/commit/ce1ce005f9fc9a147521f81de6de3c9e96d05968#diff-d680e8a854a7cbad6d490c445cba2eba )

**Comment by yatil** [comment]
@slhenry 

If you put empty lines between the list items, the content of the list items should be wrapped in a `<p>` and therefore have apt spacing. (Yes, this is one of the non-obvious things in Markdown :-D)

```markdown
- One
- Two
- Three
```

- One
- Two
- Three

vs.

```markdown
- One

- Two

- Three
```

- One

- Two

- Three

**Comment by shawna-slh** [comment]
humm -- but still marked up as a list?

**Comment by yatil** [comment]
Yes, It is `<li><p>This and that</p></li>` instead of `<li>This and that</li>` – feels slightly more semantic to me, too. Let me know if that is sufficient for your needs.

**Comment by shawna-slh** [comment]
ok I guess. :-)  /me fixed it in that doc

**Comment by yatil** [comment]
\o/
