### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website-design#134]
Currently, we are using this darker blue that W3C.org is using as a link color. It has very good contrast (12.6):

<img width="1680" alt="Example image dark color" src="https://user-images.githubusercontent.com/58862/36803565-31d5f9cc-1cb8-11e8-8736-2a4d3de9668b.png">

The “W3C blue” that is used for some background colors on W3C.org would look like this (contrast: 7.1):

<img width="1680" alt="image 2018-02-28 at 6 38 11 pm" src="https://user-images.githubusercontent.com/58862/36803608-599803a6-1cb8-11e8-888a-f634b51a24fb.png">

**Comment by yatil** [comment]
My personal opinion: I like the current version much better because it is more clear and the higher contrast makes it clear where the content is. The version with the lighter blue looks undefined and boring.

**Comment by shawna-slh** [comment]
To further clarify: The first image uses #003366 for the top header/banner with main navigation and left navigation area. That is the blue that the current W3C site uses for things such as the home page news headings. "W3C blue" is #005A9C, which is lighter and brighter.

I strongly support the WAI sub-site using colors and other means to clearly associate with the main W3C site. (I'm thrilled that we're using the same font.:) Given the situation, I prefer the darker blue for the navigation area.

This WAI redesign uses blue for large key areas (navigation). The current W3C design uses it for small, mostly minor areas—e.g., "W3C Recommendation" along the left of a TR page.

I think in this WAI redesign, the W3C blue would be too light and bright, given the large area that it covers. And that it is the background for the primary navigation.

(I also think that the darker blue better meets our visual design goal to be authoritative, credible, and reliable (and engaging, empowering, practical, clear).)

**_Most important:_ While the W3C blue just meets contrast requirements (7:1), to my eyes, it is not good enough for navigation background.**

(Possibly it might look OK to have the top layer W3C blue and the navigation layer #003366?)

I welcome other perspectives and ideas.

**Comment by koalie** [comment]
The W3C Comm webdesign TF is going to discuss this tomorrow.

**Comment by yatil** [comment]
FWIW, the color designated in the [styleguide](https://w3c.github.io/design/styleguide/#logo) as W3C is not used at all on the current website: https://cl.ly/43342Y2M381I 

(The slider on the far right highlights difference in black and sameness in white.)

Ding the same with the darker blue (currently used by WAI) reveals the headings & links as the same: https://cl.ly/2g0h2W1O1r1Z

I think W3C is associated with blue, but I doubt that it is associated with a specific hue of blue and the current W3C home page enforces that by using a lot of different variants of blue, even if you disregard the use of gradients.

**Comment by shawna-slh** [comment]
Based on W3C Comm webdesign TF minutes, we're leaving it the darker blue for now.

**Comment by brewerj** [comment]
Sorry as for some reasons the notifications of this dialog did not come through even though I was subscribed. From my perspective, "boring" is in the eye of the beholder, and I actually had that reaction to the darker blue; or rather, that it seemed very flat. Did you consider trying a shade of blue between the current darker one and the W3C reference blue? To me the dark color does not look as "living" as a shade slightly lighter would.

**Comment by yatil** [comment]
I don’t think there is any value in introducing yet another blue into the discussion. The designer picked the colors to give a certain weight. Changing the color – as shown with just replacing the W3C blue – means changing most of the other colors as well to get the same kind of hierarchy and clarity.

I really feel that the amount of work and discussion and distraction is not worth the effort at this point, considering that we did not get one word of negative feedback during the beta testing.

What @slhenry and I and others at the EOWG F2F in March discussed was changing the header to using two different blues to make the navigation more clear. That should help with the same-ness of the header area.

Early, not yet with Shawn coordinated, exploration:
![Screen Shot showing the new WAI header, with darker background on the main navigation](https://user-images.githubusercontent.com/58862/38721866-27d58044-3efc-11e8-9833-59ed14f30951.png)

**Comment by brewerj** [comment]
To clarify a few things: 
- I had not suggested adding another blue to the design, but rather making one of them not quite so dark. However, I see what you're saying about the good contrast that the darker blue gives, so I don't consider this a major concern.
- With regard to not having gotten any negative feedback on the darker color, actually I had commented on it several times in discussions about the design, but it had not been captured. My reason for directly raising it at this time was because I wanted to hear what consideration this had been given. 
- I think the color differentiation in the "early... exploration" above would probably help a lot.

**Comment by brewerj** [comment]
A separate comment related to color: at one point I think that there were one or two accent colors in consideration as part of the website palette, but I'm not seeing these used in the final design. Are you still thinking of using the accent color(s) for any information types on the website in the future? I'm not advocating for trying to add these back into the design at this time, but simply asking for a pointer in case there were specific design decisions on why not to use these, as I'd be interested for potential future reference.
