### ISSUE TITLE
Draft like Archive, on bcase pages

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#136]
@yatil , I think we want a "Draft" treatment like we've done for "Archive", with:
* "[Draft]" in title
* "Draft" yellow labely thing that's in h1
*  yellow box under h1 where we put more info

Before announcing beta, let's put that on the in-progress bcase pages.

**Comment by yatil** [comment]
Didn’t we agree to not put draft stuff on the new site?? This adds a lot of last-minute complexity.

**Comment by shawna-slh** [comment]
I was assuming that we'd have the draft revised business case on the beta site -- but maybe others were not thinking that??
I'm happy to discuss -- especially ways to avoid complexity.

**Comment by shawna-slh** [comment]
Maybe best to just leave bcase section empty for beta?

**Comment by yatil** [comment]
I don’t have strong feelings. I have added the functionality for drafts. Either we use the currently published one or the new one. We just have to decide :-D

**Comment by shawna-slh** [comment]
Proposal: For now, the beta has one bcase page. It says:

> # Accessibility Business Case

> The Education and Outreach Working Group (EOWG) is significantly revising this resource.

> The previously published version is "Developing a Web Accessibility Business Case for Your Organization" at  https://www.w3.org/WAI/bcase/

> (The unapproved, in-progress draft revision is here https://w3c.github.io/wai-bcase/business-case/ )

Let me know if you strongly disagree or want us to get more input.

Let me know if you want me to do anything to get content on that page, or anything else.

(And let's see if Sharron and EOWG can get the revised business case publishable before launch...)

**Comment by yatil** [comment]
> Let me know if you strongly disagree or want us to get more input.

As I said, I have no strong feelings.

> Let me know if you want me to do anything to get content on that page, or anything else.

I can add it.

**Comment by yatil** [comment]
@slhenry Shall I now mark it as draft, or not?
