### ISSUE TITLE
search box border contrast

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#137]
@yatil here's a reminder to make the search box have contrast of at least 3:1, ideally 4.5:1. Given how much most people want to use the search (and that it actually works well now!), I think good to make it clearly visible, and 4.5:1 would be good.

Can be just adding a border, not changing the box color itself. Let me know if you want more specifics.

from https://www.w3.org/TR/WCAG21/#non-text-contrast:

> The visual presentation of the following have a contrast ratio of at least 3:1 against adjacent color(s):
> User Interface Components
> Visual information used to indicate states and boundaries of user interface components, ...

fyi, the Low Vision Task Force considered making this 4.5:1

**Comment by yatil** [comment]
Is that for the search box in the header? I assume so.
