### ISSUE TITLE
site footer

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#138]
* "Web Accessibility Initiative" -> W3C Web Accessibility Initiative (WAI)

* "Copyright © 2017 W3C® (MIT, ERCIM, Keio, Beihang). Usage policies apply."
->```Copyright &#xA9; 2018 W3C <sup>&#xAE;</sup> (<a href="http://www.csail.mit.edu/"><abbr title="Massachusetts Institute of Technology">MIT</abbr></a>, <a href="http://www.ercim.eu/"><abbr title="European Research Consortium for Informatics and Mathematics">ERCIM</abbr></a>, <a href="http://www.keio.ac.jp/">Keio</a>, <a href="http://ev.buaa.edu.cn/">Beihang</a>) <a href="/Consortium/Legal/ipr-notice">Usage policies apply</a>.```

* delete column "Give Us Feedback"

* will have tweaked tagline wording for you soon -- it might be 2 words longer. without that middle column, should be enough space.

* change links in last column to:
** Contact WAI
** Site Map
** News
** Archive
** Resources for Roles

**Comment by yatil** [comment]
Fixed in https://github.com/w3c/wai-website-theme/commit/33732219d22b257dd88269d5167bd014bf422698
