### ISSUE TITLE
Benchmarking usability test

### ISSUE THREAD

**Issue by charlottehwise** [w3c/wai-website-design#14]
Write test plan, recruit users, and conduct benchmarking usability test (qualitative sample size) to gain insight into current pain points and uncover unknown IA issues.

**Comment by shawna-slh** [comment]
First to make clear: I think usability testing is incredibly valuable at all stages!

At the May 2016 face-to-face meeting, we noted that it is not particularly important for this project to be able to demonstrate improvement from the redesign -- thus benchmark for this purpose is not a priority.

We also discussed usability testing on the existing site and usability testing on redesign wireframes, draft ideas, prototypes, etc. We decided that it was more important to spend time and resources on later usability testing and not on the current site.

Of course, we can change that decision...

My inclination right now is to stick with it -- to not spend time and resources on testing the existing site, and to do testing on drafts/prototypes/etc.

**Comment by yatil** [comment]
We did user testing and should open a new issue if we need more user testing :-)
