### ISSUE TITLE
Decide on tagline (include? what would it be?)

### ISSUE THREAD

**Issue by happywebdiva** [w3c/wai-website-design#18]
On the current site, "WAI: Strategies, guidelines, resources to make the Web accessible to people with disabilities" is the tagline -- featured on every page near the top.  Taglines are related to visual design -- affecting perception of the site.  IMO this tagline is too blah-blah -- and thus we need to either do away with it or replace it with a very brief phrase that's in sync with our goal of "the WAI site as the #1 Go-To place for Web accessibility."  To quote Copyblogger (copyblogger.com/create-a-tagline/) :  "More often than not, [most people] get [taglines] wrong by focusing on what their product or service is and neglecting what it offers."

**Comment by shawna-slh** [comment]
I suggest that EOWG and others consider the tagline along with other aspects of the site design, including overall visual design, skip content, change design, and home page content. To do this, we need an updated visual design for folks to look at...

**Comment by yatil** [comment]
The latest homepage mockup has the following tagline:

> Strategies, standards, and resources to make the web accessible to people with disabilities.

**Comment by yatil** [comment]
Seeing no substantive discussion around this issue, and regarding the timeline of the project, I close it for now.

**Comment by shawna-slh** [comment]
+1 to closing this issue.

Recent tagline discussion is elsewhere.
