### ISSUE TITLE
Top Tasks Planning

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-website-design#21]
Charlotte and Shawn will work on this offline.

**Comment by shawna-slh** [comment]
Info in Issue https://github.com/w3c/wai-website-design/issues/13

**Comment by shawna-slh** [comment]
Joy & Chris offered to help. [e-mail with ideas for next steps](https://lists.w3.org/Archives/Public/public-wai-eo-site/2016Sep/0002.html)

**Comment by shawna-slh** [comment]
EOWG action item: https://lists.w3.org/Archives/Public/public-wai-eo-site/2016Sep/0005.html

**Comment by James-Green** [comment]
Planning complete.
