### ISSUE TITLE
Feedback box design

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website-design#27]
We currently have this feedback box, and I hope we can integrate this more in the new layout.

https://www.w3.org/WAI/EO/wiki/WAI_Website_Redesign/Feedback_Box

(Feel free to reassign and re-label as you see fit.)

**Comment by shawna-slh** [comment]
As clarified in 4 Jan teleconference, some, but not all, pages will have this box. More specifically, some pages will be in GitHub and others will not. Few will now, and more may later.

**Comment by James-Green** [comment]
visual design complete
