### ISSUE TITLE
Launch style tiles work

### ISSUE THREAD

**Issue by happywebdiva** [w3c/wai-website-design#3]
Here's an approach I'd suggest.  If you like it, I expect these need to be broken into individual backlog items, so feel free to do with this item as you see fit.  Thanks.
1. Settle on a format to give to designers.  I'd suggest the one at http://styletil.es/ -- especially the downloadable PSD.
2. Decide on time frame and other ground rules, including when needed, fine to do multiple style tiles, send results to James, know that we are very grateful for all efforts, and that we may or may not use them (however one can say this kindly).
3. Draft an email to the designers that includes these ground rules, the 3 adjective pairs we came up with, the personas, and the primary goal.  Don't weigh these volunteers down with our wiki pages, etc. -- just cut to the design chase.
4. Email the wonderful volunteers who are willing to jump in and give this a go.

**Comment by James-Green** [comment]
We decided to keep this as one backlog item - the tasks cannot stand on their own and you outlined them so well :)  The following tasks this sprint are to collect submissions and evaluate/decide.  See those here https://github.com/w3c/wai-website-design/milestone/1

**Comment by shawna-slh** [comment]
"request for submission" discussed in 27 July & 3 August teleconferences. need to include things like: volunteer, acknowledgements, permissions, expectations, etc.

**Comment by James-Green** [comment]
Invites sent out by Sharron
