### ISSUE TITLE
Translations back-end

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#31]
For many pages, we would like to have easy access to translations of that page. That involves:
* UI to easily discover and get to the translations  - in separate issue https://github.com/w3c/wai-website-design/issues/32
* backend for it

Additional info:
* Current W3C database discontinued ([e-mail](https://lists.w3.org/Archives/Public/w3c-translators/2017JanMar/0000.html)), not-yet-updated [W3C Translation page](https://www.w3.org/Consortium/Translation/Overview.html)
* [I18N ](https://www.w3.org/International/2004/06/translation.en.html)and [CSS](https://www.w3.org/Style/CSS/translating.en.html) translations pages
* outdated [WAI translating page](https://www.w3.org/WAI/translation)

**Comment by yatil** [comment]
I guess that would just be a link and a separate page with a language identifier, like the following, right?

* English: https://www.w3.org/WAI/eval/preliminary/
* French: https://www.w3.org/WAI/eval/preliminary/fr/ (or https://www.w3.org/WAI/eval/preliminary/?lang=fr)

We also have to think about how we indicate if translations are current or outdated, but that is mostly #32, I think.
