### ISSUE TITLE
Translations UI

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#32]
For many pages, we would like to have easy access to translations of that page. That involves:
* UI to easily discover and get to the translations
* technical backend for it  - in separate issue https://github.com/w3c/wai-website-design/issues/31

**Comment by James-Green** [comment]
alicia to find a page-level location for a language dropdown that will allow users to quickly change the language of a given resource.

**Comment by James-Green** [comment]
James and Sylvie will be working through how this should work and get with Alicia when ready.

**Comment by yatil** [comment]
We didn’t get to a conclusion for now, and I think it makes sense to table that until we actually _have_ translations. It is probably trivial from an implementation perspective.
