### ISSUE TITLE
Explore and define which pages to add metadata to

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website-design#33]
As discussed between @lakeen and me on Jan 6th.

  * Eric to send Laura the current metadata. ✅
  * Eric to talk to Shawn to determine the first set of pages. ✅
  * Eric/Shawn to send first set of pages to Laura. ✅
  * Laura crafting descriptions and tags (more or less) for this first set of pages.

[slh updated  ✅ on items 2 & 3]

**Comment by shawna-slh** [comment]
I did a quick first pass at [prioritizing pages for metadata](https://www.w3.org/WAI/EO/wiki/Metadata_priorities).

Anyone is welcome to change that (especially moving things up in priority).

**Comment by yatil** [comment]
I fixed the display and repaired the links.
