### ISSUE TITLE
Design Mockups: Headings & link colors [medium]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#40]
For EOWG and other input:
**1. I'm a bit uncomfortable with blue for heading level 3 and callout box headings, since blue has such strong affordance for clickable link.**

For Alicia (awesome visual designer):

2. We will also need to provide styles for more heading levels -- at least level 4.

3. Is that link text color set, or browser default? What about visited link color?

**Comment by bakkenb** [comment]
I am okay with the blue color for heading level 3. They use a very similar color all over the [WCAG 2.0 recommendation page](https://www.w3.org/TR/WCAG20/), and elsewhere I assume, so I don't see it as a problem. I think this was more of an issue back in the early stages of the internet. Open to others thoughts though.

**Comment by James-Green** [comment]
resolution to change H3 color to match same color of H1 and H2.

**Comment by yatil** [comment]
(Just noting that the TF did not think that it’s a problem as we are underlining every link in the content, and so it would be clear that the non-underlined blue headings would be no links. But now it is clear anyway.)

**Comment by aliciafrausto** [comment]
fixed
