### ISSUE TITLE
Design Mockups: In-page links [discretionary] 

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#41]
Reference: [26 Jan mockups](https://projects.invisionapp.com/share/H299QZZGZ#/screens/215895929), screen 5 of 9
Related issue: https://github.com/w3c/wai-website-design/issues/38

Maybe it's just the nature of a draft mockup, but it's not clear what that box is. I assume we will want to include a header such as "On this page" and make the links look like links.

**Comment by yatil** [comment]
I support this. <del>The box might also be on the right side of the page.</del> (Resolved for me in #38.)

We would need a title for the `<nav>` element anyway and why shouldn’t we display it, too?

**Comment by aliciafrausto** [comment]
I think adding this title this may be over-explaining and add cognitive clutter, and we did discuss this on a call. Can't remember if the group decided it is okay to leave this off. 

I will look at the link styling to see if I can increase how clickable they look.

**Comment by James-Green** [comment]
We will discuss title next week, as well as Alicia's ideas for more clickyness

**Comment by shawna-slh** [comment]
https://w3c.github.io/wai-website-components/components/preview/example-generic.html has "Page Contents" so all good

**Comment by James-Green** [comment]
in the prototype as of now
