### ISSUE TITLE
Design Mockups: Help improve page box missing [discretionary]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#42]
Reference: [26 Jan mockups](https://projects.invisionapp.com/share/H299QZZGZ#/screens/215895929)

The "Help improve this page" box is missing from some of the pages, including the Tutorials (8 of 9) and How to Manual page (6 of 9)

I assume that's just because this is a draft mockup, and it would go at the bottom of those pages. If so, please close this issue. :-)

**Comment by yatil** [comment]
Yeah, all the components can be used on all pages and in all columns. I’ll make sure that they are implemented in a flexible way.
