### ISSUE TITLE
Consider font-weight and font-family

### ISSUE THREAD

**Issue by haltersweb** [w3c/wai-website-design#44]
1) font-weight:
* Minimum font weight for text to be readable is 400 (rely on the font-weight numbers rather than names like "regular" or "book")
* For very large text >24px you can get away with 300.  But its contrast ratio minimum must be 4.5:1.
* See the second chart "Font Weight and Contrast" on my page about fonts here: http://haltersweb.github.io/Accessibility/font-sizing-and-contrast.html

2) font-family:
Some custom fonts don't render so well on a PC.  Also, browsers use poorer rendering engines than Adobe products.  Therefore you should do a test in HTML and view in IE and FF on PC.  Squint and see if it looks alright.

**Comment by yatil** [comment]
Note that we also want to limit the download size of every font we’re using. So normal, italic, bold and bold italic might be all we need. I think we don’t need to use thin (≤300) font weights.

**Comment by yatil** [comment]
From the meeting:

* WCAG 2.0 has no provision on less than normal text, so one _could_ argue we can’t use it. (I don’t.) Or we need to have a larger color contrast to meet WCAG 2.0.
* Font with less weight will be ok on higher resolution (Retina) displays but can be harder to read on non-retina screens. We might be able to send the thinner font only to retina screens.

Best is to come up with a prototype and just test.

**Comment by shawna-slh** [comment]
Prototype and more discussion in https://github.com/w3c/wai-website-design/issues/52

I hope OK to close this separate issue. Please re-open if not. :)
