### ISSUE TITLE
Code snippet colors against background

### ISSUE THREAD

**Issue by haltersweb** [w3c/wai-website-design#45]
Using code snippet syntax coloring is very important.  I'm so glad to see it here.

But the different syntax colors might cause contrast problems against the gray.

You could test all the colors, but...

...another option would be to have a button at every code snippet that changes it to black and white.  That way you can maintain the semantic color that developers are used to while solving for low vision.

**Comment by bakkenb** [comment]
I like the option that Adina is suggesting (if it is not to difficult or time consuming to incorporate. Also as long as it does not add to the clutter or complexity of the pages. Giving people these choices are good, but I don't want to sacrifice our streamlined look and feel or add too much complexity to the site.

**Comment by yatil** [comment]
I agree. Also it is not to much of an hassle to test the colors and make sure they all conform.

**Comment by lakeen** [comment]
I vote for testing the colors to keep it simple.  We're only talking about 3-4 tests.

**Comment by James-Green** [comment]
Resolution: Eric and Caleb will put the prototype together and Alicia will review the colors that come out.  No button to switch to black and white, we'll pick a palette that passes AA.
