### ISSUE TITLE
Focus state design

### ISSUE THREAD

**Issue by haltersweb** [w3c/wai-website-design#46]
I would love to see a design for the focus states for everything from navigation to links and buttons.

Remember you need unique look and feel for 4 focus states for things like navigation or radio buttons/check boxes:
* not-active focused
* active focused
* not-active not-focused
* active not-focused

**Comment by James-Green** [comment]
alicia will design these.

**Comment by aliciafrausto** [comment]
I also need to add overstate specs to some elements

**Comment by aliciafrausto** [comment]
Updated mocks

Plan for focus states for buttons and links:
Focus (Hover state + default browser styling, per G165. Example is mocks similar to mac/chrome ) 

Question about radio buttons - is best practice also to use browser default states?
