### ISSUE TITLE
Design Mockups: Text and Background Combinations (minor error)

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-website-design#47]
Minor fix...

On the [Text and Background Combinations pallets](https://projects.invisionapp.com/share/H299QZZGZ#/screens/215895933), the visual color of the black background box for the "yellow on dark grey" combination is the wrong color. The hex code is correct, the contrast ratio is correct, but the color used in the box is actually #1D1D1D instead of #3B3B3B.

Please adjust the color visually to be 3B3B3B.

**Comment by James-Green** [comment]
alicia will fix

**Comment by aliciafrausto** [comment]
fixed
