### ISSUE TITLE
Design Mockups: The Plan for Anchors and Back to Top links

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-website-design#48]
[strong]
In some of the current resources, there are a lot of anchor links and "back to top" links throughout. Will that functionality remain in the new design? If so, I would like to see a mock-up of how those would look visually so that they could be implemented consistently throughout the site.

**Comment by yatil** [comment]
+1

**Comment by lakeen** [comment]
+1

**Comment by AndrewArch** [comment]
+1 from me too

**Comment by James-Green** [comment]
alicia will look at back-to-top links design.  anchors seem to be covered by in-page navigation.

**Comment by aliciafrausto** [comment]
I added a back to top link here, but I've seen some nice-to-use floating style Back to Top links, I'm wondering if that is an implementation we should explore?
https://visa.invisionapp.com/share/YPAVCUZA9#/screens/223719157

**Comment by James-Green** [comment]
I like the idea of a floating link, let's discuss next week.

**Comment by aliciafrausto** [comment]
Added an example of floating style back to top link to invision mockup above.
