### ISSUE TITLE
Design Mockups: Font sizes

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website-design#49]
* The font size in the footer should be at least 14px. It appears that it’s smaller.
* I think in general for me the font size could be larger, but that’s a personal preference.

**Comment by AndrewArch** [comment]
On a related note, is the H3 the same size as text? While a different colour and weight, I'd also prefer a slightly larger size, especially as the colour has a low contrast with the text colour.

(seems to be related to #40)

**Comment by James-Green** [comment]
alicia will bump up the size of "status draft and editors:" to match that of footer (dark gray background) text.

**Comment by James-Green** [comment]
alicia will consider andrew's comment when she looks at the fonts.

**Comment by aliciafrausto** [comment]
footer text bumped up:
https://visa.invisionapp.com/share/YPAVCUZA9#/screens/223719157
