### ISSUE TITLE
Content Inventory (for IA)

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-website-design#5]

**Comment by shawna-slh** [comment]
https://www.w3.org/WAI/sitemap.html is updated.

Planned new resources:
- more Tutorials
- Inclusion doc draft: http://w3c.github.io/wai-inclusion/ (project page links to requirements, etc: https://www.w3.org/WAI/EO/wiki/Accessibility_and_Inclusion)
- Accessible [UI Components List](https://www.w3.org/blog/wai-components-gallery/) (title to be changed) 
- possibly 1-3 more Tips for Getting Started (draft of 3 new ones: http://w3c.github.io/wai-quick-start/)

Planned changes:
- https://www.w3.org/WAI/intro/accessibility.php to be updated and then _not_ need to point to http://www.w3.org/standards/webdesign/accessibility
- Working Group, Interest Group, Task Force, etc. pages (listed under [WAI Groups in sitemap](https://www.w3.org/WAI/sitemap.html#groups)) might become out of scope depending on future W3C website decisions.

Changes to IA:
- WCAG 1.0, ATAG 1.0, and UAAG 1.0 resources should have much less predominance. They still need to be find-able, but not primary. 2.0 versions should be primary.

Possible new resources:
- more/better intro guidance on WAI-ARIA
- guidance on specific topics [ask Denis...]

**Comment by charlottehwise** [comment]
Will probably use DynoMapper to do this--I am trying it out using the free trial version now.

**Comment by shawna-slh** [comment]
Discussion moved to https://github.com/w3c/wai-website-design/issues/17 ?

**Comment by James-Green** [comment]
moving to next Sprint, with plans to finish during September.

**Comment by James-Green** [comment]
complete, Charlotte will convert to sharable format in next task.
