### ISSUE TITLE
Design Mockups: Ideas for fly-out menu on sub pages?

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website-design#50]
As some people can’t use fly-out menus, so clicking on the main menu item should either

1. keep the fly-out menu in place or
2. open a sub-page with the fly out menu inline.

**Comment by James-Green** [comment]
table until we discuss the IA.

**Comment by shawna-slh** [comment]
/me not think dependent on IA... It's a UI issue regardless of IA

**Comment by James-Green** [comment]
TF agrees on going with eric's option 1 above.  click on main item again closes menu, as does clicking outside menu.  if this ends up being problematic with prototype, we will readdress.

**Comment by James-Green** [comment]
leaving issue open until we see prototype from Eric so we don't forget.

**Comment by shawna-slh** [comment]
(leave open just so we remember to evaluate it from a usability & accessibility perspective)

**Comment by yatil** [comment]
My prototype is in #102.
