### ISSUE TITLE
Design Mockups: Font h4, h5, h6

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website-design#51]
I’d like to see h4, h5 and h6 – we really use them sometimes :-o

**Comment by lakeen** [comment]
+1

**Comment by James-Green** [comment]
alicia will mock up

**Comment by aliciafrausto** [comment]
invision mock:
https://visa.invisionapp.com/share/YPAVCUZA9#/screens/223719078

zeplin, for dev: https://zpl.io/ZyIDQg
