### ISSUE TITLE
Disclaimer

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website-design#55]
A common way to show disclaimers:

* Potentially with (optional) expand/collapse functionality
* Potentially alternative layout for more important (legal…) disclaimers.

(Came up in w3c/wai-policies-prototype#1, also applies to http://github.com/w3c/wai-eval-tools.)

**Comment by aliciafrausto** [comment]
Mockup shows:
- A legal/very important disclaimer as a sidebar
- A less important disclaimer that is included in the footer

https://visa.invisionapp.com/share/YPAVCUZA9#/screens/223719157_Page_Layout_-_Sidebar

**Comment by shawna-slh** [comment]
Great first start. Let's see later when we polish the visual deign and look at specific content, if we want any tweaks.
