### ISSUE TITLE
Navigation idea

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#57]
**Here is a [Navigation idea (straw proposal)](http://htmlpreview.github.io/?https://github.com/w3c/wai-website-design/blob/master/nav-idea.html)** based on:
* Alicia's visual design ([teaked verison for Nobo Sans fon](http://htmlpreview.github.io/?https://github.com/w3c/wai-website-design/blob/master/font-check.html)t)
* Charlotte's IA drafts ([pdf](https://lists.w3.org/Archives/Public/public-wai-eo-site/2017Feb/0001.html), [xls&cvs](https://lists.w3.org/Archives/Public/public-wai-eo-site/2017Feb/0007.html)) and usability testing results
* Card sort at f2f with James and folks ([images](https://lists.w3.org/Archives/Public/public-wai-eo-site/2016Dec/0000.html), [text in .doc](https://lists.w3.org/Archives/Public/public-wai-eo-site/2016Dec/0003.html))

This would be for an interim navigation while we are making more significant changes to content, e.g., reorganizing the pages under How People with Disabilities Use the Web.

Feel free to tweak directly via GitHub (or pull request if you can't Commit directly)

**Comment by shawna-slh** [comment]
If we want to refine this idea, here are some thoughts and questions:

1. **Implement \ Tutorials, Tips, Examples** -- When the Components list is done, maybe put Examples as it's own sub-section?

2. **Implement \ How to reference the guidelines and How they are developed** -- I put these there here because they are directly related to the Guidelines; however, they are not directly related to Implementing.  Perhaps they should go elsewhere -- or even maybe not have in primary nav, and just link all places relevant, e.g., Policies pages?

3. **Promote / Managing Accessibility** -- Managing Accessibility kinda goes with Implement, but maybe better here because Implement focuses more on the actual developing. I'm inclined to put it under Promote, and just make sure there are plenty of links to it in relevant places, such as the main Intro.

4. **Evaluation and Report Language (EARL) Overview** doesn't fit smoothly anywhere. The audience is tool developers. Possibly it would be better in the Evaluate section -- however, that mostly has a totally different primary audience. (Also, I like having ARIA under the "specifications" subheading, and it's good for it to have another bullet. ;-) So I'd be inclined to have it under Implement.

5. Selecting and Using Authoring Tools for Web Accessibility -- Maybe not have in main nav – archive until it gets updated?

6. **Accessibility Principles** -- Later when rejigging content, make Accessibility Principles an easy direct landing page, and then add it to the top level navigation.

**Comment by James-Green** [comment]
comments incorporated into current IA.
