### ISSUE TITLE
Navigation coding

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#58]
Hey, @vuxcaleb (& @yatil ), what do you think about getting going with coding the navigation?

I think it would be very useful to have that in place for working on the IA/nav refinement and for usability testing! It's so much easier to look at navigation ideas in a prototype rather than a static outline.

Note this related issue: https://github.com/w3c/wai-website-design/issues/50

**Comment by yatil** [comment]
https://w3c.github.io/wai-website-components/components/preview/full-example.html

**Comment by yatil** [comment]
Did some more work on the navigation area today, but there is an open issue for the meeting :-)
https://github.com/w3c/wai-website-components/issues/8

**Comment by yatil** [comment]
Closing this as it looks like this is not the active discussion thread anymore.
