### ISSUE TITLE
Home page - footer big nav?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#64]
Nav – what about having a big nav in footer? I see that done fairly commonly these days, and I do find myself using it. Given our biggest issue is getting people to know about and find the breadth of WAI resources, it seems that might be a good idea.

**Comment by yatil** [comment]
Examples: 
* https://www.microsoft.com/
* https://www.att.com

**Comment by yatil** [comment]
Good idea; we can iterate on it when we are further along the development.

**Comment by shawna-slh** [comment]
more examples:
* http://www.adobe.com/
* https://www.verizonwireless.com/
* https://www.amazon.com/

It is very common these days.

**Comment by aliciafrausto** [comment]
we agreed to come back to this after the IA is completed.

**Comment by VivienneConway** [comment]
I'd agree, provided there is a skip link or at least an ARIA landmark for the footer so that people don't have trouble navigating their way to the footer

**Comment by yatil** [comment]
Note that the footer navigation on adobe.com, for example, does not have the same links as the main navigation. I think this pattern is OK for websites with thousands of pages where you want people to have quick access using the footer, but the WAI site is not such a site. :-)

**Comment by James-Green** [comment]
none of the sites linked above have the same links in the footer as in the main nav. they use the footer nav for a different purpose entirely.  Unless we are trying to duplicate or main nav in the footer (which is **not** a common practice), I suggest we drop the idea of having a footer nav.

**Comment by shawna-slh** [comment]
At this point, I feel like the main nav is good, and additional mega nav in footer is not needed.

Since I opened this issue, I'm closing it. :-)

If anyone feels differently, feel free to re-open.
