### ISSUE TITLE
Home page - What is WAI & above the fold

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#65]
I have mixed reactions to seeing above the fold only the nav and the one first section.
Pro: nav gets more attention.
Con: "What is WAI" is below the fold.

Also, "What is WAI" is static; whereas most of the other content is changing. Therefore, I wonder if "What is WAI" should have different visual treatment and visual placement? Maybe top right under nav?

**Comment by yatil** [comment]
*cough* [There is no fold](https://www.lukew.com/ff/entry.asp?1946) *cough* ;-)

**Comment by aliciafrausto** [comment]
The mock matches the priority we made together in the workshop for the home page. If "What is WAI" moves up, keep in mind you will be moving the less static content lower on the page, which may not be what you intended. Or, we can break the full width featured row to only use 2/3 of the row, with the WAI definition in the right column. I think this will result in a more cluttered layout, so I would suggest we leave it as is. 

Either way, I just need clear direction if a change is required here. It will likely affect multiple elements on the homepage.

**Comment by yatil** [comment]
I am against making changes like that right now. I think it is more important to tell people about accessibility than what about what WAI is (most probably don’t care much). Also, we have an “About WAI” link in the navigation.

Let me first build every page; we can then make changes if we feel it is important. People know how to scroll, the stuff visitors see at first glance is different on every device, so there is no fold.
