### ISSUE TITLE
Home page - no "learn more" links

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#66]
Don't need (or want:) "Learn more" links anywhere. We'll use in-line links, as currently in https://www.w3.org/WAI/#highlights

**Comment by aliciafrausto** [comment]
removed from mocks, updated zeplin link. @yatil Do you need to make this update anywhere?

**Comment by yatil** [comment]
I still see the read more links [in the Zeplin](https://app.zeplin.io/project/591da5955b71d83479c8abdd/screen/592839d4c012138d3c4fd010) – but no need to update it there, I can just make the edits in the HTML/CSS.
