### ISSUE TITLE
Home page - featured video

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#67]
I like that "Feature Resource" and "Tip of the Day" make it clear that these are changing sections. How about do a similar thing with the Perspectives Videos? Maybe change "Web Accessibility Perspectives" to "Featured Video"? (And hopefully in the future we'll have Easy Checks Videos for there, too. :-)

**Comment by shawna-slh** [comment]
Alicia: OK.

**Comment by bakkenb** [comment]
+1

**Comment by aliciafrausto** [comment]
Changed in mocks and zeplin, I think we can close this one.
