### ISSUE TITLE
Home page - sponsors & funders

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#68]
Sponsors and Funders laid out as is was confusing. It took me a while to figure out that it is a 2-column list organized alphabetically.  Would be good to do differently so that it doesn't look like some are higher than others. Also, fyi, we hope to use logos for most of those in the future.

**Comment by shawna-slh** [comment]
Alicia: logos would be great

**Comment by James-Green** [comment]
TF agreed Alicia to design for text, if we get logos, we'll do that as available.

**Comment by shawna-slh** [comment]
I understood that we agreed to go with a single column list as long as they are text. Correct?
(and we can revisit if/when we get logos)

@yatil - Do you need Alicia to update the mock-ups to reflect that? Or is this documentation enough?

**Comment by yatil** [comment]
I can remove the classes from the list without Alicia doing anything ;-)

I think the four columns (goes to two in narrow viewports) looks OK for now: http://w3c.github.io/wai-website/

**Comment by yatil** [comment]
Done.
