### ISSUE TITLE
nav - distinguishing links/page titles, esp. when wrapped

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#70]
Some links/page titles will wrap, so need to have separator lines &/or bullets &/or hanging indents -- or something to make it clear what is a new title or not.

fyi, /me finds in current prototype it's a little hard to distinguish the items even without the wrapping issue

I think clearer separation of the items will improve usability and accessibility :)

(Existing WAI site uses lines, e.g., left nav of https://www.w3.org/WAI/training/accessible )

**Comment by aliciafrausto** [comment]
added lines between items
https://visa.invisionapp.com/share/RUCY9YUQE#/223719150_Menu_-_Expanded
https://zpl.io/aRX95N2

**Comment by James-Green** [comment]
Shawn suggests slightly darker lines and Eric suggest removing last line and maybe first (below heading) per Alicia's discretion.

**Comment by shawna-slh** [comment]
Discussion on 11 Aug of having only one level of nav per fly-out and having tertiary nav in additional fly-outs, as is https://w3c.github.io/wai-website-components/components/preview/example-home.html#

**Comment by lakeen** [comment]
I believe it was also suggested to add  on focus underlines for a secondary nav item that is a link and > for secondary nav item that has a flyout.  See Microsoft site for example: https://www.microsoft.com/en-us/defaultb.aspx

**Comment by shawna-slh** [comment]
@yatil - What about making the flyout boxes wider -- at least for the first few menu items? That would limit wrapping and make reading easier. :-)

**Comment by yatil** [comment]
@slhenry It would also mean longer distance for the mouse when opening sub-menus. It’s a tradeoff. How much more space would be appropriate? 20% 50%?

**Comment by shawna-slh** [comment]
Good point. Well, the sub-menus would open with no horizontal mouse movement, but longer mouse movement to open an item in a submenu. ;-)

/me too fried to think about it now... :(
