### ISSUE TITLE
nav - current page indicated

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#71]
e.g., when in the "Tips for Developing" page, and then drop-down the main nav, make it clear that is the current page.

If need more explanation or input, ask James and Brent.

(Existing WAI site has current page background match the main page background, and chevron -- e.g, left nav of https://www.w3.org/WAI/training/accessible )

**Comment by aliciafrausto** [comment]
updated mocks and zeplin link to show current page state. 
https://visa.invisionapp.com/share/RUCY9YUQE#/223719150_Menu_-_Expanded
https://zpl.io/aRX95N2

**Comment by James-Green** [comment]
TF okay with yellow triangle as shown

**Comment by shawna-slh** [comment]
Discussion on 11 Aug of having only one level of nav per fly-out and having tertiary nav in additional fly-outs, as is https://w3c.github.io/wai-website-components/components/preview/example-home.html#
