### ISSUE TITLE
[Nav EOWG] general on early August iteration

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#73]
Issue to collect comments on https://docs.google.com/spreadsheets/d/1pqcSChcWZwTShpov34jDfvX2E-jW6_M5khV38D53Qqk/

Put general comments here. <br>For specific comments, please:
1. see if an [issue already exists for the topic](https://github.com/w3c/wai-website-design/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%5BNav%20EOWG%5D)
2. if not, create a [new issue with title "[EOWG-Nav]..."](https://github.com/w3c/wai-website-design/issues/new?title=[Nav%20EOWG]%20@@specific_topic@@)

**Comment by yatil** [comment]
Almost all of the navigation options are still too long in my opinion. I don’t have good ideas for shortening them, but it is a lot of reading, and then the titles are still not clear.

**Comment by vmmiller** [comment]
I find the following menu items too long and I think they are not simple/easy to understand:
- Interaction Design on how to meet WCAG 
- Content Creation in How to Meet WCAG 
- Visual Design in How to Meet WCAG Reference
- Developing in How to Meet WCAG Reference

Others which are too long and could perhaps be shortened:
- Developing Accessibility Presentations & Training 
- Web Accessibility Laws and Policies.  Couldn't this simply be "Accessibility Laws and Policies"?
- First Checks for Common Accessibility Problems
- How do People with Disabilities Use the Web?
etc.

**Comment by vmmiller** [comment]
Probably, just needs to be fixed but let me signal it anyway:
The menu items on the far right are off my screen because they are too long.

**Comment by vmmiller** [comment]
A bright side comment:  I really like the new design.  It's light, clear and refreshing.  I like the way the navigation is displayed, xyz & xyz.  

However, I have a nagging problem.  For me, I think that "Standards/Guidelines" is not "evident" as it is not part of the main navigation whereas, in the old site, this was a clear link to this important - and well sought after - information.  In my opinion, visually, this is no longer evident.  I tend to ignore the information squeezed into  header/footer stuff, so I really looked into the menus for this important link and only later found it.  Perhaps, it's just me :)

**Comment by vmmiller** [comment]
Note:  "Perspectives Videos" is displayed as a link in the google spreadsheet whereas the online version says "Users perspective videos".  I think the latter is clearer than "Perspectives Videos".

**Comment by vmmiller** [comment]
(Functionality/Fix It issue) Under "Test & Evaluation", hovering over "Evaluation tools", there is another level of navigation.  This level is lost for me, as the menu item is only partially visible on my laptop.

**Comment by yatil** [comment]
@vmmiller Yes, I know that the navigation is not fully functional yet, including the position on the screen.

**Comment by shawna-slh** [comment]
Thanks for the thoughtful review and input, Vicki!

I'm shortening a few of the items.

About the Perspectives Videos &mdash; The content is broader than *user* perspectives -- a key aspect is showing the additional benefits to website owners, which is related to business case. I'd rather not re-open the name of this unless people feel strongly.

I'm closing this issue, and moved one of your comments to a new issue. https://github.com/w3c/wai-website-design/issues/80
