### ISSUE TITLE
[Nav EOWG] Write and design: include Tutorials

### ISSUE THREAD

**Issue by notabene** [w3c/wai-website-design#74]
For _Write and Design_, the [nav featured on gspread](https://docs.google.com/spreadsheets/d/1pqcSChcWZwTShpov34jDfvX2E-jW6_M5khV38D53Qqk/edit#gid=660009004) mentions:

>  @@ include Tutorials, or not 'cause they're mostly developer info and the write & design info is linked from the Tips pages?

I would vote **for** including them in the menu as for other chapters they are included (consistency), also because it's easier for most people to look into a menu rather than browse a whole page.

**Comment by yatil** [comment]
-1 as I find the tutorials to not have significant information for designers and writers. They are quite technical.

**Comment by notabene** [comment]
OK. Maybe after launch we could work on some designer- and writer-specific tutorials then.

**Comment by yatil** [comment]
The tutorials (as they are now) were envisioned as a venue for developers, but I agree that we should have some more information about designing and writing for accessibility, apart from the tips.

**Comment by notabene** [comment]
Closing for now. Let's talk about it after launch.

**Comment by shawna-slh** [comment]
re-opening for now, so we see that there are opinions on it -- until we update the proposed nav to take out the questions. :-)
