### ISSUE TITLE
Navigation - keyboard

### ISSUE THREAD

**Issue by VivienneConway** [w3c/wai-website-design#75]
Hi all
This might not be appropriate here, but wanted to make a couple of notes.  I find that the top navigation is not operable via keyboard, while it is by mouse.  This might just be in the prototype, but thought I'd mentioned in just in case.

The other issue I'm seeing is that on my monitor's resolution (100%, text normal size), the navigation is all on top of each other and a real mess.  I'm not sure why this is occuring, but it only happens in Internet Explorer.  Chrome and Firefox seem fine.

Regards
Vivienne

**Comment by yatil** [comment]
Hi Vivienne,

the prototype is not yet keyboard navigatable as this is not the final navigation design and the Internet Explorer fallback is also not yet implemented. We’re working on it :-)

Eric
