### ISSUE TITLE
Link naming

### ISSUE THREAD

**Issue by VivienneConway** [w3c/wai-website-design#76]
In the section with the icons 'audit, design, develop, laws &policies', can we please rename those links from 'learn more'?  Suggestion: learn more about audits, learn more about design etc.?

Regards
Vivienne

**Comment by yatil** [comment]
Hi Vivienne,

the links are the complete sections, including the header. So the section the link links to is already included in the link and it is not the “classical” stand-alone “learn more” link.

Eric

**Comment by VivienneConway** [comment]
Perfect, thanks Eric.  I just cringe every time I see ‘learn more’ – an automatic reflex (smiling)

 

 

Please be advised that I check my emails at approximately 9am and 4pm each day (more or less).  If you require assistance sooner, please feel free to telephone.

 

Regards,

 

Vivienne Conway, Ph.D., B.IT (Hons), MACS (Snr) CP, AALIA(CS)

Director

 

Web Key IT Pty Ltd

PO BOX 681 Wanneroo, WA 6946

Phone:    (08) 9206 3987

Mobile:   0415 383 673   

Email:       v.conway@webkeyit.com <mailto:v.conway@webkeyit.com>  

Website:  www.webkeyit.com <http://www.webkeyit.com/>  

 

 



 

This communication, including any attachments, is intended solely for the named addressee. It is confidential and may be subject to legal professional privilege. If you are not the intended recipient, please contact me immediately by reply email, delete it from your system and destroy any copies. This email is subject to copyright, no part of it should be reproduced, adapted or transmitted without the prior written consent of the copyright owner. Any views expressed in this message are those of the individual sender and may not necessarily reflect the views of Web Key IT Pty Ltd.
