### ISSUE TITLE
[Nav EOWG] Links to Quickref

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website-design#77]
As we are obviously deep linking into the quickref application from the main navigation, I think this might be disorienting for users as the URL has none of the categories in it.

However, there are other considerations:

1. How do we highlight the proper navigation? The quickref does not know if someone comes from the navigation menu or somewhere else on the web. 

2. What would be the canonical position in the AI (not navigation) for the quickref? It is not yet clear from what I’ve seen.

3. While the direct link to specific quickref pages is useful for some people, it’s probably confusing for people not used to WCAG, and we need to make clear (visually and through text) that those links are of the last resort/direct to specification kind.

4. What do we do with WCAG 2.1 coming up? Will we have two links in each category? (Please not.)

I _think_ we should have information boxes with links to the quickref. Instead, that would give us space to explain what it's for and we would also have fewer menu items, which is always good :-)

**Comment by bakkenb** [comment]
I think I need more detail and discussion to process this issue. I get the nature of it, but need more explanation outside of this thread. Thanks for adding.

**Comment by shawna-slh** [comment]
+1 for not a direct link -- so we'll need to figure out how to do it

We'll also need to work with AG WG and others about WCAG 2.1 through the redesign.

**Comment by vmmiller** [comment]
I think deep linking into Quick Ref from the main navigation could lead to confusion (different look, hard to get back, and for the newcomer, possibly, a little overwhelming).  I think along the comments of @yatil above.  I even wonder if it is possible to place such links in the secondary page rather than the main navigation menu.

**Comment by yatil** [comment]
We discussed that in the meeting yesterday and agreed that we want to remove the links from the navigation and instead link from sidebar boxes or through other mechanisms.
