### ISSUE TITLE
[Nav EOWG] Approaches for Interim Repairs

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-website-design#78]
I am not sure I like "Approaches for Interim Repairs" under the main navigation of "Plan & Manage". This is not where I would look for a resource about doing some quick initial fixes to get me going. 

That said, I am not sure where it should go elsewhere. Doesn't really fit in any other location either. So maybe leave it where it is. Just wanted to post this issue as it kind of sticks out to me as the only thing that doesn't seem in the right place.

**Comment by shawna-slh** [comment]
Note that the content does not cover making the actual fixes. It's about planning and managing the fixes. :-)

+1 to not fitting anywhere else.

This might be a good candidate for one of the featured resource sections. (I'm not sure it's substantial enough for the top one, but maybe good for one of the middle ones.)

**Comment by yatil** [comment]
> This might be a good candidate for one of the featured resource sections. (I'm not sure it's substantial enough for the top one, but maybe good for one of the middle ones.)

+1

**Comment by bakkenb** [comment]
> Note that the content does not cover making the actual fixes. It's about planning and managing the fixes. 

Good point. I am okay with it where it is after this point was made clear to me.

**Comment by yatil** [comment]
What about naming it: Planning Interim Repairs or something like that? (or: Plan fixing accessibility bugs? bug fixing strategy?
)

**Comment by nrhsinclair** [comment]
What about "Identify High Priority Issues" or  "Identify High Priority Issues and Fixes" or "Address Critical Issues"

**Comment by shawna-slh** [comment]
See document content: https://www.w3.org/WAI/impl/improving

**Comment by yatil** [comment]
For reference, here is the title discussion from 2016: w3c/wai-planning-and-implementation#63

**Comment by bakkenb** [comment]
As I revisit the document and read through the content, I now have a better understanding of what this resource contains. I was initially under the impression that it was similar to Easy Checks, in so much that it would have tasks for someone to do to check accessibility and make fixes. However, upon deeper review of the resource, I now see that it is actually guidance for planning to making beginning repairs up front and then guidance into full on accessibility work in the future. I should have read the resource content more carefully before adding this issue.

I do feel that this resource IS named appropriately. And now I do believe it IS in the correct location of Plan & Manage navigation. This resource is about planning and managing what to do first if you are new and need immediate assistance. 

I am closing this issue. If others still feel like the resource name needs to change, feel free to re-open the issue.

**Comment by nrhsinclair** [comment]
As I have looked at this resource more and the proposed navigation (and title considerations) I also think this resource link is not in the right place. It should be moved further down in the list, either as an option in the Plan, Implement, Sustain list, possibly add Repair to this - Plan, Repair, Implement, Sustain or possibly move after "Involving Users for Better, Easier Accessibility". The current location near top, does not seem to be the right place. Considering the interim repairs should fit into the overall planning.

**Comment by shawna-slh** [comment]
The intention was for this document to help people in the situation "Help! We have to make our website accessible and I don't even know where to start! I gotta do something now and fast!"

So these people will not yet be thinking about overall planning. The intention was for this to be the first place to start, and then when the fire is out, they can move onto bigger picture planning.

**Comment by shawna-slh** [comment]
@nrhsinclair  - do you have specific suggestions for helping communicate that?

**Comment by yatil** [comment]
I think this document could also go in one of the four front page buckets… We’d have some more space to explain what it does and an icon could help. I don’t care where the document is in the menu. Maybe we could name the item “First steps towards an accessible website” (but shorter :-D).

**Comment by shawna-slh** [comment]
+1 for home page middle section

added to https://github.com/w3c/wai-website-design/issues/82

**Comment by slhenry** [comment]
https://github.com/w3c/wai-website-design/issues/82

**Comment by shawna-slh** [comment]
Had a good chat with Norah and we are both comfortable leaving as is for now, and revisiting as a lower priority after launch. (unless usability testing shows it's a really big issue, then reconsider)

(I think it would be good to rethink the whole Plan & Manage section, including possibly integrating Developing Org Policies into main resource. However, I think ***definitely*** lower priory than lots of other things we should do first.)

**Comment by bakkenb** [comment]
+1 to Leaving as is. Thanks
