### ISSUE TITLE
[Nav EOWG] Where would main navigation links point to?

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website-design#79]
In case of missing JavaScript or people just immediately clicking onto the main navigation items, we need to lead them to a website probably duplicating the sub-menu navigation. Any ideas on that?

**Comment by shawna-slh** [comment]
/me assumes page replicating the navigation

possibly a single page for each -- except that to see the whole navigation, users would have to click and back button 9 times -- don't want that!

so probably have it all on one page, and deep link into the specific section they click on. Then they can scroll to see all of the nav on one page.

**Comment by shawna-slh** [comment]
Note that the primary navigation will be simpler than the full site map...

(E.g., mobile sub-pages and older user pages not in main nav, but should be in full site map.)

**Comment by yatil** [comment]
> /me assumes page replicating the navigation

> possibly a single page for each -- except that to see the whole navigation, users would have to click and back button 9 times -- don't want that!

I really, really don’t want to do that. It will be misleading as the user jumps to an anchor down the page and misses the navigation. It is also something that is not done on any other website. If they want to see the whole page navigation they can go to the sitemap (which does not need to have more information than the navigation by default, the rest can be in disclosures).

Also if all top-level links point to the same page, they will be indicated as “visited” to people using screen readers (we won’t indicate that visually) even if they did only go to one section of the page.

> Note that the primary navigation will be simpler than the full site map...

Can you send me a link to the full sitemap? I just want to double-check that I have the most recent version.
