### ISSUE TITLE
[Nav EOWG] Standards/Guidelines lost

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#80]
From Vicki (in [general issue](https://github.com/w3c/wai-website-design/issues/73#issuecomment-324495711))

> I have a nagging problem. For me, I think that "Standards/Guidelines" is not "evident" as it is not part of the main navigation whereas, in the old site, this was a clear link to this important - and well sought after - information. In my opinion, visually, this is no longer evident. I tend to ignore the information squeezed into header/footer stuff, so I really looked into the menus for this important link and only later found it.

**Comment by shawna-slh** [comment]
Background: Judy had an overall comment about the new design and navigation not looking like a standards organization as opposed to a commercial company. She *likes* the modern design, yet feels the design, nav, and content needs stronger connection to W3C. She or I will make specific comments elsewhere. 

Related to this issue:

I think moving Standards/Guidelines into the main nav might help a little.

**Comment by bakkenb** [comment]
Strong +1 to Vicki's comment and Shawn's Option (alt3) in the spreadsheet. 

Once I saw what was proposed in the [new alternative 3 visual mockup](https://w3c.github.io/wai-website-components/components/preview/example-home-alt3), it struck me as odd that we were not including the standards/guidelines in the main navigation in earlier versions. It is one of the main parts of the site that people are looking for and it should be in the main navigation. I agree with Vicki that it gets mostly overlooked when it is up in the top header navigation area ([see current mockup](https://w3c.github.io/wai-website-components/components/preview/example-home)).

I also like combining "Write & Design" / "Code & Develop" together under the new "Design & Develop" main navigation category as they are the most similar and have the least resources. It looks better when they are combined.

**Comment by shawna-slh** [comment]
Standards/Guidelines last item in main nav.

Resolved in [25 August telecon](https://www.w3.org/2017/08/25-eo-minutes.html)
