### ISSUE TITLE
[Nav EOWG DESIGN] Navigation changes for secondary nav

### ISSUE THREAD

**Issue by aliciafrausto** [w3c/wai-website-design#84]
@yatil, here is the zeplin link for the menu changes: https://zpl.io/2yXz8Jb

**Comment by yatil** [comment]
Thanks @aliciafrausto !

**Comment by yatil** [comment]
I have made changes :-)

**Comment by yatil** [comment]
(Some refinement is pending for when I make the menu keyboard accessible and also take a look at the positioning especially of the right-hand main menu items.)
