### ISSUE TITLE
[Home page] specific links only

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#87]
Brent says of the Tip of the Week:
> Would link directly to the tip content only. Recommend not cluttering the area with links to additional resources/information (“more design tips”). Let them discover this on their own.

Shawn reply:
+1 for linking directly to the tip itself for more info.
There's also the issue that we have 3-6 other Tips pages, and if just link to one, some users will assume that's all we have.
**[Alicia <- James]** I guess we need revised design to accommodate this.
**[Usability Testing - Charlotte]** We might want to see in usability testing if they notice that there are other Tip pages available...

Brent says of the Web Accessibility Perspectives videos:
> Recommend NOT including the “See All Perspectives Videos” button. If this is left there users will be more apt to look at the rest of the videos in the very first sitting. Then for the next nine months there will be nothing new for them in this spot. If they do that on their own by browsing through the resource that is fine.

Shawn reply:
Well, actually, I hope they find them so compelling, that they look at all of them right away! Yes I agree that we don’t need the See All button, because the rest will be easily discover-able from the one. (Also, btw, I dream of having other videos...)
**[Usability Testing - Charlotte]** We might want to check in usability testing if indeed they easily discover the others.
**[Alicia <- James]** I guess we need revised design to accommodate this. We might not need a button at all, if we go with something like https://github.com/w3c/wai-website-design/issues/89

**Comment by yatil** [comment]
- -1 to link to a part of the page (relatively strong)
- -1 to not having more tips links, as it is good to show the specific and the broad here. (relatively mild)
- ±0 on having link to all videos, I think it is useful. There are links from other parts of the target page. However, there is additional information on the video detail page that might not be seen if we put the video on the home page. (Do we want to do that or do we want the preview picture to only link to the detail page?)

**Comment by VivienneConway** [comment]
Personally I like have a link to all the videos, as I might want to spend considerable time on the resource at one time and would like to know everything available - then I can come back whenever I want.  As a service provider, if I refer a client to the resource, I want them to be able to easily see all we offer, they might not come back and check out other things later and would miss out on great information. (IMHO)

**Comment by yatil** [comment]
Good point, @VivienneConway.

**Comment by aliciafrausto** [comment]
Tip of the Week:
What is the decision here? Remove/change the 'More Design Tips' link? What is the actual content you guys think will be displayed here? Should the tip itself be styled as a link instead?

Link to all videos:
I see multiple opinions on whether we are keeping this, not sure what the decision is. Also not sure a new mockup is necessary regardless, can easily hide the second button without it affecting other things on the page.

**Comment by yatil** [comment]
@aliciafrausto Yes, we don’t need mockups for both issues. We just need a decision and I can easily implement it.

@slhenry Can you please decide for the UT ASAP.

**Comment by shawna-slh** [comment]
> -1 to link to a part of the page (relatively strong)

I understand concern with linking into middle of a page. However, I think (relatively strongly) that they need to be directed to an explanation of the specific tip. The tips need more explanation to be understood and implementable. I hope we get some feedback on this in usability testing.

> -1 to not having more tips links, as it is good to show the specific and the broad here. (relatively mild)

A concern is linking only to one of 6+ tips, though. E.g., when we only link to Design Tips, then potentially not clear there are others. Related issue https://github.com/w3c/wai-website/issues/2
Again, will be interesting to see what we learn from usability testing.

±0 on having link to all videos, I think it is useful. 

Per above, Brent and I think they are easily discover-able. I hope we get a chance to see whether or not they are from usability testing.

**Comment by shawna-slh** [comment]
> What is the actual content you guys think will be displayed here?

The content will be 4-7+ words, *all* shorter in length than "Provide sufficient contrast between foreground and background".

**Comment by shawna-slh** [comment]
Unfortunate that we're in a position to make last minute decisions without comfortable discussion and consideration. Anyway, it's just for usability testing for now, and we can address with more user input after next week!

I propose for this usability testing prototype:

Link to all videos:
Not include.

Tip of the Week:
Yes, Remove 'More Design Tips' link. 
Yes, it should be styled as a link or otherwise provide affordance that it's a link. Maybe it shouldn't be underlined by default - just for aesthetics. Maybe just underlined on hover or focus. Maybe include chevron (>>) or arrow (>) at the end of it like is currently after "More Design Tips >". I welcome suggestions. (Or, happy to make tentative decision if preferred.)

**Comment by yatil** [comment]
> Yes, it should be styled as a link or otherwise provide affordance that it's a link. Maybe it shouldn't be underlined by default - just for aesthetics.

I’m unable to introduce yet another different looking link style, so I added an underline to the tips text.

**Comment by yatil** [comment]
I think this issue is resolved with the new home page mock-up :-)
