### ISSUE TITLE
[Home page] Perspectives Video text - tagline?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#89]
I suggest that we include the tag line:
> essential for people with disabilities and useful for all

Here is a longer and short option:

**Keyboard Compatibility**
All functionality must be usable with the keyboard. That is, users can access and move between links, buttons, forms, and other controls using the Tab key and other keystrokes. Websites should not require a mouse. Learn more about how [Keyboard Compatibility](https://www.w3.org/WAI/perspectives/keyboard.html) is essential for people with disabilities and useful for all.

**Keyboard Compatibility**
All functionality must be usable with the keyboard. Websites should not require a mouse. Learn more about how [Keyboard Compatibility](https://www.w3.org/WAI/perspectives/keyboard.html) is essential for people with disabilities and useful for all.

**Comment by bakkenb** [comment]
+1 to longer option. I think the longer amount of text will balance out the size of the video to the right.

**Comment by yatil** [comment]
OK with any text provided :-D

**Comment by VivienneConway** [comment]
+1 to the longer explanation

**Comment by shawna-slh** [comment]
@yatil - Looks like go with the longer version for usability testing.
