### ISSUE TITLE
[Home page] Video - end of play

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#90]
On the [home page](https://w3c.github.io/wai-website-components/components/preview/example-home.html), users can play a video. Currently at the end, it brings up thumbnails for 4 videos; and only one is ours. Can we set it so that it only shows the other videos in our playlist?

Maybe Caleb knows how to do this? :-)

**Comment by yatil** [comment]
Yes, we can. Do we want users to be able to play a video on the home page in the first place? Or might they miss out on our secondary information that we provide? We could link an image of the video to the details page.

**Comment by yatil** [comment]
(Consider linking to the details page especially because we have additional accessibility features there, like transcript and Audio description. I feel strongly we don’t want to replicate them on the home page because it would bloat the page load time.)

**Comment by shawna-slh** [comment]
I actually didn't expect them to play on the home page -- that surprised me.

I'm fine with it linking to the page.

I suggest that we do that for usability testing, and **@charlottehwise and all can see what users think of that in usability testing**. :-)

**Comment by yatil** [comment]
I had to assume from the static site image. Will replace with a screenshot on the homepage.
