### ISSUE TITLE
[Home page] minor tweaks

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#92]
I think these are minor and don't need other input or discussion. However, I am totally open to it if needed! James, if you think these don't need discussion, would you comment and assign to Eric to implement?

Ref: https://w3c.github.io/wai-website-components/components/preview/example-home.html on 18 Sept

* "See All News and Announcements" -> "See All News"  (we don't include the announcements in that archive)

* Delete "See Past Events" (we're not maintaining a list of past events anymore)

* "Get WAI Announcements" -> "Get WAI News and Announcements" (since the "highlights" were changed to "news" :-)

**Comment by bakkenb** [comment]
+1 to all of these.

**Comment by yatil** [comment]
> Delete "See Past Events" (we're not maintaining a list of past events anymore)

I think we should have a list of past events, with linked slides/videos/…

> "See All News and Announcements" -> "See All News" (we don't include the announcements in that archive)

OK

> "Get WAI Announcements" -> "Get WAI News and Announcements" (since the "highlights" were changed to "news" :-)

If we say “see all news” on the top, we should have “get WAI news” there. (Is there a difference between News & Announcements? Does anyone coming to the page understand that difference? If we could have just one term it would be preferable over two similar terms.)

**Comment by VivienneConway** [comment]
+1 to all

**Comment by shawna-slh** [comment]
> I think we should have a list of past events, with linked slides/videos/…

I can't see that we can have that anytime soon. Too many other higher priorities.

**Comment by yatil** [comment]
This was assigned to me without a real resolution. I have no idea what to do. :-/ @slhenry 

> I can't see that we can have that anytime soon. Too many other higher priorities.

Well, we are testing features that we can then add content to while it happens. We don’t need to go and backfill the content for launch (which would be super useful eventually, IMHO), but we can add the content and show it when we have content for it in the future. For the user testing, the question is if we want to have it here, and I hear a no, but I did not see a clear resolution to this either.

**Comment by yatil** [comment]
(please re-assign once we have a clear resolution)

**Comment by James-Green** [comment]
I agree with Eric.
I think we should drop the term "Announcements" and let "News" cover it all.
I think we should have an archive of events.  We can either start going forward or at least try to put a couple  recent in there to get it started.

**Comment by shawna-slh** [comment]
fyi, we had an [Events page](https://www.w3.org/WAI/events.html) that listed meetings and WAI training (not all presentations by WAI staff), and it wasn't a priority to maintain it the last couple of years. If someone wants to take on filling it in, I'd be fine with that -- but I can't in the foreseeable future. There is also the [W3C Calendar of Events](https://www.w3.org/participate/eventscal.html).

I do not want to link to an incomplete or out dated listing. (I mean for the real site, that's fine for the prototype for usability testing/)

**Comment by shawna-slh** [comment]
The link "Get WAI Announcements" is currently under the Announcements heading, so it might be weird to have it say just "Get WAI News". And also people are used to "Get WAI Announcements". But I don't feel strongly about this.

**Comment by shawna-slh** [comment]
There is not consensus above; however, I'm pretty sure no one objects to any option for the usability testing. So in the interest of just getting something in place for the usability testing, let's go with:

* "See All News and Announcements" -> "See All News"

* Leave "See Past Events" _(Eric, please don't spend any time putting content there. I don't think we'll have it at launch anyway, and there are more important things for you to do.)_

* "Get WAI Announcements" -> "Get WAI News"

Eric, when you're done, feel free to un-assign yourself, put please leave it open for us to revisit later.

**Comment by yatil** [comment]
I made the changes (to the prototype – I won’t update the content of the components library for now).

**Comment by yatil** [comment]
There were a lot of discussions in the meantime and we are implementing a different home page. I’ll close that for now, and we will create new issues if needed.
