### ISSUE TITLE
[Home page] WAI intro blurb

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#94]
Latest home page prototype: https://w3c.github.io/wai-website-components/components/preview/example-home.html
_(fyi, I think the font will be the same as throughout -- not bigger as it seems right now)_

**What is the W3C Web Accessibility Initiative (WAI)?**

WAI develops resources to make the web accessible to people with disabilities, including:

- guidelines widely regarded as the international standard for web accessibility

- support materials on understanding and implementing web accessibility

WAI encourages participation from around the world.

**Comment by yatil** [comment]
> (fyi, I think the font will be the same as throughout -- not bigger as it seems right now)

I like the bigger font; it is a nice counterweight to the tips.

> WAI develops resources to make the web accessible to people with disabilities, including:
> * guidelines widely regarded as the international standard for web accessibility
> * support materials on understanding and implementing web accessibility
> WAI encourages participation from around the world.

I feel strongly that we don’t want to have a list in there. 


Just a brainstorm rewording, not feeling strongly about it:

“WAI develops internationally recognized standards for web accessibility and support materials on understanding and implementing web accessibility. We encourage participation from around the world.”

(I do not particularly like the “around the world” part, it sounds oddly specific. We also encourage participation from different groups and industries and with diverse backgrounds, and we might want to include that..)

**Comment by shawna-slh** [comment]
Would like to come up with different heading than "What is the W3C Web Accessibility Initiative (WAI)?"

Maybe general
* About the W3C Web Accessibility Initiative (WAI)"
* Web Accessibility Initiative (WAI) at W3C

or more specific, e.g., along the lines of:
* WAI in W3C's Web for All Mission /  WAI Supports W3C's Mission of Web for All

**Comment by shawna-slh** [comment]
brief notes from Judy: bigger than guidelines.... supports W3C Web for All mission...

**Comment by VivienneConway** [comment]
I'm also not fond of the 'around the world' as it seems odd, keeping in mind the W3C's membership.  I like the idea of "We encourage participation from different groups and industries and with diverse backgrounds".  Maybe the drop the 'also' from the previous suggestion.

**Comment by yatil** [comment]
“Web for All mission” sounds weird to me.

Proposal: 

> Web Accessibility is a core principle of a Web for All. In W3C, WAI develops internationally recognized standards as well as educational support materials that help understand how to best address web accessibility. Participants from around the world participate in our working groups to support this principle.

I wonder if instead of “web for all” we could introduce our “Essential for some, useful for all” lingo that many people like.

**Comment by VivienneConway** [comment]
My problem with ‘Web for All” is that is the name of the W4A (Web For All) Conference.

(Edited by @yatil to remove email footer.)

**Comment by shawna-slh** [comment]
Wording not in latest design, so closing this issue.
