### ISSUE TITLE
[Nav] Tutorials specific

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#95]
... @@

<s>and move Media out</s> done

**Comment by yatil** [comment]
Media has been moved out of the wai-design prototype.

Please specify 

> … @@

or close the issue :-)

**Comment by shawna-slh** [comment]
To clarify: move media out from under Tutorials, not out of the prototype all together. :-)

> Please specify
… @@

Not this week :-) -- after usability testing push.

(I mentioned briefly in [22 Sept discussion](https://www.w3.org/2017/09/22-eo-minutes.html#item18), and said let's deal with that later)

**Comment by yatil** [comment]
I would just like to know what “… @@” means. Is that the suffix discussion? Guide/Intro/Overview?
