### ISSUE TITLE
[home page] Feature Resource

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#97]
I think make "Featured Resource" text less pronounced. Minor -- and I don't feel strongly.

Alicia <- James

**Comment by James-Green** [comment]
I emailed this to her while we wait to get her on the participants list..

**Comment by aliciafrausto** [comment]
Dropped the text size down in the mocks to 14px for this text and the featured video text. 

https://visa.invisionapp.com/share/YPAVCUZA9#/234693428_Home_Page
https://zpl.io/bzLjgXV

@yatil - assigning to you so you can update the actual site.
