### ISSUE TITLE
[Nav] To WGs and such

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website-design#99]
Need to make it easy to get to WG pages. [Nav spreadsheet](https://docs.google.com/spreadsheets/d/1pqcSChcWZwTShpov34jDfvX2E-jW6_M5khV38D53Qqk/edit#gid=887243996) has

>  @@ are these fly-outs, too, or just single click to one page?

and unfilled out info under Get Involved and About W3C WAI

**Comment by yatil** [comment]
There are no drop downs from the utility nav, maybe we can have a quick nav to the WG pages, but I wonder if that stuff should be inside About WAI. Do we need a specific section for Working Groups/TFs organizational stuff?

**Comment by yatil** [comment]
I think we are going without a flyout. It will be two clicks to get to a group page. If we need other things, we need to re-evaluate after the launch.
